### ISSUE TITLE
Ruby Ternary doesn't identify symbols correctly

### ISSUE THREAD

**Issue by brodock** [rouge-ruby/rouge#1038]
```ruby
variable = something ? :from : :to
```

```ruby
 puts Rouge.highlight('variable = something ? :from : :to', 'ruby', 'html')
<span class="n">variable</span> <span class="o">=</span> <span class="n">something</span> <span class="p">?</span> <span class="p">:</span><span class="n">from</span> <span class="p">:</span> <span class="ss">:to</span>
```

**Comment by vidarh** [comment]
I *think* this is as simple as doing this to :ternary:

```ruby
       state :ternary do
-        rule(/:(?!:)/) { token Punctuation; goto :expr_start }
-
         mixin :root
+        rule(/:(?!:)/) { token Punctuation; goto :expr_start }
       end
```

Basically, symbols never get matched because they're checked after the rule that terminates the ternary. 
I need to do more testing before I'm happy about doing a pull-request for it. An alternative fix would be to to a more aggressive lookahead rule than just checking there's no second colon, but I don't like unnecessary look-ahead..

**Comment by jneen** [comment]
You're welcome to tinker with these definitions, but be warned there be dragons here. Please make sure to check the ruby sample file (`spec/samples/ruby`) - there are a *lot* of edge cases.

**Comment by vidarh** [comment]
@jneen Sure, worth testing if it makes a difference. The lexer already for the most part will tolerate a lot of missing elements in expressions anyway, so I'm not sure it would, but I'll definitively do some testing - I know how hard the Ruby grammar is to get right...

**Comment by pyrmont** [comment]
This definitely looks like a messy area. Consider:

```ruby
 a = false ? :b :c
```

In `irb` (in 2.7.0), Ruby doesn't treat `:c` as a symbol but rather as `:` and `c`. I think @jneen's sense that an intermediate state is necessary might be correct.
