### ISSUE TITLE
Objective-C highlighter fails on untyped methods

### ISSUE THREAD

**Issue by mulle-nat** [rouge-ruby/rouge#1076]
```objc
- foo:(id) foo
{
   [self bar:foo];
}
```

will produce syntactically incorrect Objective-C output (notice the `- -`):

![grafik](https://user-images.githubusercontent.com/1381995/51742659-bc6fb280-209a-11e9-9b99-de4c6dad5522.png)

**Comment by pyrmont** [comment]
The error seemed to be caused by the fact that [the Objective-C method definition regex](https://github.com/rouge-ruby/rouge/blob/e957c740ca85b3a96f2cea1e8e1eafbf9cb2abc4/lib/rouge/lexers/objective_c.rb#L158-L166) was calling `Rouge::RegexLexer#recurse` with `nil` as the argument for untyped methods.

I think this may actually indicate a bug in `Rouge::RegexLexer#recurse` (or at least a potentially horrible gotcha). When invoked with `nil` as its argument, it appears to recurse using the last matched token from the input stream. That's why you saw `-` twice.

Anyway, I've made a PR in #1118 to only call `Rouge::RegexLexer#recurse` if the input is non-nil.
