### ISSUE TITLE
Golang syntax highlighting ignores newlines

### ISSUE THREAD

**Issue by calini** [rouge-ruby/rouge#1097]
Hello! I wanted to post some Go snippets on my Jekyll powered website, but I see the syntax highlighter just ignores the newlines and renders the code on one line.
This does not reproduce for other programming languages, or when not mentioning the programming language after the opening `~~~`.
(Fun fact, Go is rendered in a decent fashion if marked as C)

**Comment by pyrmont** [comment]
Our sample file is rendering without a problem and I can't reproduce this problem. Do you have more details?

**Comment by calini** [comment]
Not really, since I have not tinkered with the configuration, especially nothing related to code highlighting/rendering. I can provide links to places where it shows up: [link on my website](https://ilie.io/2018/how-to-download-or-use-this-theme/), [link to .md source].(https://github.com/calini/calini.github.io/blob/master/_posts/2018-06-10-how-to-download-or-use-this-theme.md)

**Comment by pyrmont** [comment]
Thanks! That's helpful. Will have an investigate!

**Comment by pyrmont** [comment]
Hmmm, it looks fine in [this snippet]. And it worked fine when I used `rougify`.

I noticed that the symbol used for the code fences differs between Go and the other languages. If you use `~` or `\`` for all three are the results the same?

**Comment by pyrmont** [comment]
Hmmm. I cloned the Git repo and the problem seems to be the way in which the HTML is being output.

The default rendering puts all tokens in their own `<span>` tags. With Go code, the newlines in the code block are also wrapped in these tags and that's causing them not to display. If you look at the HTML for the Java and C code, you can see the newlines there are _outside_ the `<span>` tags.

Not sure how to fix it yet but I think we're getting closer.

**Comment by pyrmont** [comment]
It just occurred to me that newlines are significant in Go in a way they aren't in Java and C. The fact the lexer is matching these newlines explicitly is probably what's causing the difference.

**Comment by pyrmont** [comment]
https://github.com/rouge-ruby/rouge/blob/e957c740ca85b3a96f2cea1e8e1eafbf9cb2abc4/lib/rouge/lexers/go.rb#L152

The 'problem' is here. Other lexers tokenise whitespace as `TEXT` whereas the Go lexer uses `OTHER`.

This becomes an issue when it's being rendered as TEXT tokens are not wrapped in tags at all. This is important because of this CSS rule:

https://github.com/calini/calini.github.io/blob/fec7770d0b8cd896db7232d9f315c917f003249e/assets/scss/_syntax-highlighting.scss#L32

I'm not sure which is correct; arguably a newline at the end of a statement isn't really 'text' and it's also a problem in this specific instance because of the CSS rules.

**Comment by calini** [comment]
I could just fix it in my fork but that means whoever is pulling a theme that uses Rouge will deal with the same thing. Should I fix it and do a pull request on it?

**Comment by pyrmont** [comment]
I had a look at [the description of the tokens](https://github.com/rouge-ruby/rouge/wiki/List-of-tokens) in the wiki and `Other` is described like this:

> Token for data not matched by a parser (e.g. HTML markup in PHP code)

Pygments has [the same description](http://pygments.org/docs/tokens/).

To my mind, that's not an accurate description of whitespace in Go. That makes me feel confident that changing the token to `Text` is the proper approach (there is actually a `Text::Whitespace` token but I think at this stage it's enough to have the Go lexer be consistent with other lexers).

I'll update and submit a PR.
