### ISSUE TITLE
When inside single quotes, Perl tokenizes \ as an error

### ISSUE THREAD

**Issue by miparnisari** [rouge-ruby/rouge#1163]
Problem:

![image](https://user-images.githubusercontent.com/5374887/59175038-c9041d00-8b08-11e9-98fb-0b8395f98d76.png)

I tried adding the following rule as the 3rd rule of states `:sq` and `:dq` and it fixes it, but of course IDK if this is the right solution.

```ruby
      state :sq do
        rule /\\[']/, Str::Escape
        rule /[^\\']+/, Str::Single
+        rule /\\/, Str::Single
        rule /'/, Punctuation, :pop!
      end

      state :dq do
        mixin :string_intp
        rule /\\[\\tnr"]/, Str::Escape
        rule /[^\\"]+?/, Str::Double
+        rule /\\/, Str::Single
        rule /"/, Punctuation, :pop!
      end
```

![image](https://user-images.githubusercontent.com/5374887/59175071-fbae1580-8b08-11e9-9697-49e3e98fb6df.png)

**Comment by pyrmont** [comment]
B'oh—well that's a silly mistake. I think the fix for `:sq` is right but I'm less sure about `:dq`. When I try a very rudimentary print statement at the command line with Perl then passing a double-quoted string with a single backslash omits from the output the character that was escaped. So we probably want to highlight both the backslash and the immediately following character with the `Str::Escspr` token.

**Comment by pyrmont** [comment]
I should be able to fix this soon.
