### ISSUE TITLE
minimum lines before enabling line numbering

### ISSUE THREAD

**Issue by psifertex** [rouge-ruby/rouge#1249]
I'm interested in a feature where I could enabling line numbers only for snippets longer than some minimum number of lines. I'd like to be able to manually use block codes and for small snippets (one or two lines in my case) not enable line numbers and automatically enable them for larger snippets. 

This is of course manually solvable by specifying lineos on each block (or at least it will be for users from jekyll once https://github.com/rouge-ruby/rouge/pull/897 gets accepted), but even if that gets merged it's still tedious.

**Comment by jneen** [comment]
This sort of feature seems more appropriate for Jekyll than for Rouge.

**Comment by ashmaroli** [comment]
@psifertex How do you write code-blocks in your pages? If you're using triplets (i.e. enclosed within pairs of either <code>\`\`\`</code> or `~~~`), then the rendering would be handled by `kramdown`. Or if you use the Liquid tag,
`{% highlight %}`, then the rendering is handled by Jekyll itself.

Since Rouge will only provide formatters for a limited set of basic use-cases, the best route would be to approach `kramdown` for further inputs or write a Jekyll-plugin depending on the use-case.

**Comment by psifertex** [comment]
I'm usually using pairs of triple backticks, so I will go follow up with kramdown. Thanks for the quick response!
