### ISSUE TITLE
Underscore in Markdown attribute starts italic sequence

### ISSUE THREAD

**Issue by Krinkle** [rouge-ruby/rouge#1341]
**Name of the lexer**: Markdown

**Code sample**

```markdown
>
> One day, a [link](https://example.org){:target="_blank"} was made
>
```

**Screenshots**

<img width="716" alt="Screenshot 2019-10-05 at 18 03 57" src="https://user-images.githubusercontent.com/156867/66258229-7c6cdd80-e79a-11e9-9748-baf1106bbca3.png">

**Additional context**

This uses Kramdown-style attributes, as used by Jekyll and GitHub Pages.

See also https://github.com/sublimehq/Packages/issues/2117.

**Comment by pyrmont** [comment]
Thanks for filing the issue, @Krinkle. This is a tricky one. As your issue alludes to, this isn't really a failure of the lexer to parse Markdown's emphasis syntax correctly; it's really a failure to parse Kramdown's attributes syntax. This is something they've added to their Markdown implementation, not something part of Markdown itself.

The Markdown lexer does include two custom elements that aren't part of Markdown: YAML frontmatter and fenced code blocks. YAML frontmatter lexing seems to be there for historical reasons, fenced code blocks because they're supported by almost all Markdown implementations.

As far as I can tell, Kramdown's attributes syntax doesn't have the same broad adoption as fenced code blocks. If we were to support this, I think the better way to do it would be to create a Kramdown lexer that subclasses the Markdown one. The attribute syntax (both both [block-level](https://kramdown.gettalong.org/quickref.html#block-attributes) and [span-level](https://kramdown.gettalong.org/quickref.html#inline-attributes) could be added that way. See the [API Blueprint lexer](https://github.com/rouge-ruby/rouge/blob/d31841900ff675661d124e82f8b2d854fe11cb87/lib/rouge/lexers/apiblueprint.rb) for an example of a lexer that extends the Markdown lexer.
