### ISSUE TITLE
Bug/Request: quad-backtick code blocks in markdown lexer

### ISSUE THREAD

**Issue by Ravlen** [rouge-ruby/rouge#1439]
The markdown lexer should allow code blocks that have quad backticks, which is used when you need to encapsulate a triple backtick codeblock. For example, you can see it works fine in GitHub:

````markdown
This is how you create a codeblock in markdown:

```yaml
---
one: Mark McGwire
two: Sammy Sosa
three: Ken Griffey
```

This is more text.
````

As you can see, it doesn't work with Rouge:

<img width="1182" alt="Screen Shot 2020-02-12 at 16 09 26" src="https://user-images.githubusercontent.com/36979740/74311133-12042380-4db2-11ea-9a04-2003567efb08.png">

**Comment by pyrmont** [comment]
I think this should probably be marked as a bug. The CommonMark† spec provides that [fenced code blocks](https://spec.commonmark.org/0.29/#fenced-code-blocks) can contain more than 3 tildes.

_† I realise that CommonMark and Markdown are technically different but since CommonMark is the one with a proper spec, it seems logical to use it when trying to write a lexer._

**Comment by Ravlen** [comment]
Yeah, after I clicked submit I realized I should have started with the bug template, thanks for updating it for me!
