### ISSUE TITLE
Allow highlighting of specific region

### ISSUE THREAD

**Issue by sdalu** [rouge-ruby/rouge#1652]
When doing syntax highlighting on code fragment that are used as examples,
it is often useful to further highlight some specific code region that will be explained later or to indicate dummy variable/function that will need to be replaced.

For example in the configuration below the part that will need to be customized will be underlined as per the picture below
~~~
Host cottage.example.com
  IdentityFile ~/.ssh/my_other_private_key
  Port 8080
~~~

![Screenshot_2020-12-18 SSH](https://user-images.githubusercontent.com/1355524/102624591-803d1380-4144-11eb-8bd4-7d188cd20a25.png)

This would require an optional escape mechanism that is independent of the lexer, the set of escape caracters should be selected by the user to avoid any parsing problem within its code fragment, here: $( )$
~~~~
Host $(cottage.example.com)$
  IdentityFile $(~/.ssh/my_other_private_key)$
  Port $(8080)$
~~~~

**Comment by jneen** [comment]
@sdalu Have you taken a look at the `escape` lexer? I think this might meet your requirements. I used it in my thesis to highlight individual code sections. But by doing something like: `Rouge::Lexers::Escape.new(start: '$(', end: ')$', lang: my_lexer)`, you'll have a lexer that creates special "escape" tokens that are passed through the formatter unchanged. You'll have to enable it on the Formatter though, since it is usually unsafe to pass through untrusted code unescaped: `Rouge::Formatter.allow_escape!` if you're the one in control of all of your code snippets.

**Comment by jneen** [comment]
This would actually require you to do something lik `IdentityFile $(<span class="emphasis">)~/.ssh/my_other_private_key$(</span>)`, and then add your own css rules for `.emphasis`, but we currently don't have a concept of "emphasis" that works across formatters, or that the Themes know enough about to highlight properly.

**Comment by sdalu** [comment]
@jneen Thanks, I can work with that!
(enabling is done using `Rouge::Formatter.enable_escape!`)

Perhaps a note about this particular lexer in the README could also be useful to others. It still would be nice to have a dedicated region highlighting lexer not requiring unsafe escape.
