### ISSUE TITLE
Is Rouge unmaintained?

### ISSUE THREAD

**Issue by xairy** [rouge-ruby/rouge#1700]
Hi,

I was wondering if Rouge is not maintained anymore? AFAICS, no PRs have been reviewed/merged since the beginning of February. And the CI is broken.

Please don't take this issue as a complaint. I understand how hard it can be to maintain an open-source project based only on self-motivation. I want to clarify the current status and understand whether it makes sense to expect new releases.

Thanks!

CC @jneen @dblessing @gfx

**Comment by dblessing** [comment]
@xairy 

In short, Rouge is maintained. Although, it's currently only me who is active and even then I haven't been able to dedicate much time recently. 

CI is broken because Travis changed the OSS model. I've opened a case with them to grant us OSS status which should give us a bucket of minutes each month but I haven't heard back. You can see some discussion about this in a recent PR - https://github.com/rouge-ruby/rouge/pull/1690. 

There are a few other engineers at GitLab who plan to start helping with Rouge, but due to broken CI and other priorities we've been slow to get started. 

Thanks for reaching out. Please be patient, and feel free to ping me on issues/PRs as needed. It helps remind me to work on Rouge when I get time.
