### ISSUE TITLE
Pascal lexer: strange highlight of buttons.pp

### ISSUE THREAD

**Issue by Alexey-T** [rouge-ruby/rouge#1842]
**Name of the lexer**
Pascal

**Code sample**
Lazarus file:
https://gitlab.com/freepascal.org/lazarus/lazarus/-/blob/main/lcl/buttons.pp
I see how it's rendered on site, is it using Rouge lib?
It's wrong.

1. why "types" id is hilited?
2. why "type" keyword is not hilited?
3. why "function"/"procedure"/"constructor"/"destructor" keywords are not hilited?
4. why comments `// text` and `{ text }` are not pale?

**Additional context**
none.

**Comment by tancnle** [comment]
@Alexey-T I think GitLab has recently switched from `rouge` to [`highlight.js`](https://highlightjs.org/). See this GitLab [issue](https://gitlab.com/gitlab-org/gitlab/-/issues/346257) for more information.

**Comment by joshgoebel** [comment]
Take a close look at the issue, not even feature flagged yet (according to the checklist)... so I'd say this ball is still in Rouge's court at the present.

**Comment by tancnle** [comment]
Thanks for looking into @joshgoebel. I have verified the status of the feature flag via our internal tooling and can confirm it is enabled globally on `gitlab.com`. It is most likely that the checklist on the issue was not updated accordingly.

In my local development environment, I have experimented with the feature flag toggle on (Highlight) and off (Rouge) (see screenshot).

| Rouge | Highlight |
|---|---|
|![rouge](https://user-images.githubusercontent.com/756722/176065946-65d74cb4-0b66-4615-b3d8-ab2ee0f9be60.png)| ![highlight](https://user-images.githubusercontent.com/756722/176065984-bf6341c0-3c94-44c2-baad-72fb472c76cd.png)|

Looking at the source code rendered with Highlight JS, I can see that GitLab has picked up the wrong language, `puppet` instead of `pascal` 🤔. The syntax highlight with Highlight JS [looks fine](https://codepen.io/tancnle/pen/KKoKPgp) outside the context of the GitLab editor.
 
![puppet](https://user-images.githubusercontent.com/756722/176066859-feb7522d-8735-4d54-a1e6-5fb04783e0b9.png)

**I think this is an issue within GitLab, or at least on how it maps the file extension with the language syntax.** I would raise an issue in GitLab to investigate further.

**Comment by Alexey-T** [comment]
Pascal extension is .pas, Puppet is .pp, so for file 'buttons.pp' detection is wrong.

**Comment by joshgoebel** [comment]
> Pascal extension is .pas, Puppet is .pp, so for file 'buttons.pp' detection is wrong.

For Free Pascal `.pp` is a totally valid and sometimes used extension (as we see here).  This is one problem with extensions as solo auto-detect heuristics, **they are not high enough fidelity on their own** as there is often overlap.  _No language truly owns any extension._

> Looking at the source code rendered with Highlight JS, I can see that GitLab has picked up the wrong language, puppet instead of pascal

Thanks for digging deeper here.  This would have been my next guess had I known for sure that Github HAD completed the transition as it's a common issue - people using the wrong grammar and then getting the wrong results.

---

This is probably a case where what GitLab should do is use extension as a limiter and then use our auto-detection abilities to make a final decision...   IE:

- GitLab consults a table to learn that `pp` might mean : Puppet, Pascal or Pink unicorns
- GitLab asks Highlight.js to highlight the code informing us it might be `puppet`, `pascal` or `pinkunicorn`...
- We analyze the source and decide which of the 3 languages is a "better fit"

Our auto-detect often works very well in this specific type of situation with a tiny subset of languages to decide between.

**Comment by joshgoebel** [comment]
But as the issue isn't a rouge issue I think perhaps this could now be closed and the discussion moved to Highlight.js GitHub issue or a GitLab issue?

**Comment by tancnle** [comment]
> This is one problem with extensions as solo auto-detect heuristics, they are not high enough fidelity on their own as there is often overlap.

Totally 👍🏼 `Rouge` uses a number of [factors](https://github.com/rouge-ruby/rouge/blob/master/lib/rouge/lexer.rb#L145-L164) besides filename to apply the appropriate lexer. This implementation still fails in this case 🤔.

```shell
./bin/rougify guess buttons.pp
{ tag: "puppet", title: "Puppet", desc: "The Puppet configuration management language (puppetlabs.org)" }
```

Highlight.js on the other hand pick up the correct language.

```node
node
> const hljs = require('highlight.js');
> const fs = require('fs');
> fs.readFile('buttons.pp', 'utf8', (err, data) => { console.log(hljs.highlightAuto(data).language) })
undefined
> delphi
```

> But as the issue isn't a rouge issue I think perhaps this could now be closed and the discussion moved to Highlight.js GitHub issue or a GitLab issue?

Looking close at the GitLab [implementation](https://gitlab.com/gitlab-org/gitlab/blob/mastert/app/assets/javascripts/vue_shared/components/source_viewer/source_viewer.vue#L44), I think the problem is due to `Rouge` and how it is wired in GitLab. It appears that GitLab uses `Rouge` to detect the language and passes that information to `Highlight.js`. `Rouge` detects `puppet` and the frontend [does not perform](https://gitlab.com/gitlab-org/gitlab/blob/maste/app/assets/javascripts/vue_shared/components/source_viewer/source_viewer.vue#L145-151) further language detection.

**Comment by joshgoebel** [comment]
> I will raise an additional issue on GitLab to investigate a proper integration.

Please link that here... I'm curious what you think a "proper integration" might look like... :-)

It seems the problem here is that Rouge isn't aware that `pp` can ALSO mean Pascal...?   Or is it and it just decided this was not Pascal?

**Comment by tancnle** [comment]
> Please link that here... I'm curious what you think a "proper integration" might look like... :-)

Yep, will do.

> It seems the problem here is that Rouge isn't aware that `pp` can ALSO mean Pascal...? Or is it and it just decided this was not Pascal?

Of all the factors that `Rouge` checks, they all return `Puppet` lexer 😢 I am curious about how the auto-detection is done in `Hightlight.js` 🤔

**Comment by joshgoebel** [comment]
> Of all the factors that Rouge checks,

What are "all the factors"?  It seems like your filename database is simply lacking the connection - or else you're limited in the fact that you're only allowed to return a single canonical answer instead of "it might be A or B"...?

>I am curious about how the auto-detection is done in Hightlight.js 

Very roughly: The parser matches "tokens", things that look like a language... comments, strings, keywords, naming conventions, operators, syntax... all these things have specific relevance values... for auto-detect we run EVERY grammar against a snippet... and the grammar that has the most relevance wins.

It's not perfect.

**Comment by joshgoebel** [comment]
A better approach would be to use outside heuristics (stack overflow tags, gitlab file extensions, etc) to 'hone in' on a few choices, and then let us decide which of those limited choices is correct.  We perform much better in that type of scenario, ie... "is this Pascal or Puppet"...

**Comment by tancnle** [comment]
> What are "all the factors"?

`Rouge` does mimetype, filename, modeline, shebang and finally some manual [disambiguation steps](https://github.com/tancnle/rouge/blob/master/lib/rouge/guessers/disambiguation.rb#L84-L96).

**Comment by tancnle** [comment]
> Where is the code for shebangs?

In this file, https://github.com/tancnle/rouge/blob/master/lib/rouge/text_analyzer.rb

**Comment by tancnle** [comment]
@Alexey-T FYI, we have bumped the version of Rouge in GitLab to fix the language detection for Free Pascal. Could you kindly check if the highlight works correctly this time?

**Comment by Alexey-T** [comment]
It's OK now, thanks!
