### ISSUE TITLE
Architecture for Themes and the HTML formatter for 2.0

### ISSUE THREAD

**Issue by jneen** [rouge-ruby/rouge#192]
Open thread to discuss interface and format changes, combining discussions from #154, #155, #149, #117, #145, #139, and #104.

**Comment by Arcovion** [comment]
To summarise:
* An option to add the CSS class to the `pre > code` tag instead of the `pre` tag would be nice as it would help migrating from other highlighters and is what [W3C suggests](http://www.w3.org/TR/2011/WD-html5-author-20110809/the-code-element.html).
* Line numbers are not semantic at the moment, provide more options.
* The `pre > code` tag should be styled as `display: block`, this is what other highlighters do and it  allows backgrounds to be applied to the `code` tag, however:
* If using the `pre > code` tag, applying the background to the code tag may not be desirable, instead I think it's better to apply the background to the `pre` tag as is being done currently.
* An option to disable backgrounds being added when using generated themes would be nice, this also removes the need for `rouge` to worry about the last two points and leaves it up to the user.

I'm going to refactor `middleman-syntax` soon and lock to the latest `rouge` version, but I'm being stubborn and using `1.7.3` atm as I liked the ability to apply the CSS class to the `code` tag. :P

**Comment by jneen** [comment]
Whether the W3C suggests it or not, it broke user code, so I want to be careful about it in the future.

**Comment by jneen** [comment]
I'm working on a refactor that will hopefully encourage more custom subclasses of `Formatters::HTML` to take some of the feature-pressure off the class.
