### ISSUE TITLE
Request: Solarized theme

### ISSUE THREAD

**Issue by NARKOZ** [rouge-ruby/rouge#229]
http://ethanschoonover.com/solarized

**Comment by jneen** [comment]
I believe we have one?

**Comment by jneen** [comment]
Ah, there's `base16.solarized`.  I think one of my contributors might have one.  I seem to remember @Arcovion using a solarized theme?

**Comment by Arcovion** [comment]
I use `monokai.sublime`, but there are many solarized themes on google that are compatible: https://gist.github.com/nicolashery/5765395
https://github.com/gthank/solarized-dark-pygments

**Comment by MarcoDeBortoli** [comment]
@jneen @Arcovion I'm not quite sure how those works though. I saved the style from the command line but it doesn't render as expected. What's the right procedure to follow?

**Comment by jneen** [comment]
I'm not sure what system you're using with rouge, but you need the stylesheet to be scoped to the same context that the html is rendered into.

**Comment by MarcoDeBortoli** [comment]
@jneen I'm using jekyll with the [lanyon](http://lanyon.getpoole.com/) theme. I generated the syntax.css file with the following command:

```bash
$ bundle exec rougify style base16.solarized.dark > css/syntax.css
```

And [this](https://gist.github.com/MarcoDeBortoli/eb5e95109cc42173d043) is my `_config.yml`

Still I don't get a solarized version of my code. Am I missing something?

**Comment by jneen** [comment]
Ergh, jekyll puts stuff in a very specific context. You should be able to pass a `--scope <selector>` argument to that `rougify` command, so for example if they wrapped it in `<pre class="highlighted">` you'd run:

``` bash
$ rougify style --scope pre.highlighted base16.solarized.dark
```

**Comment by MarcoDeBortoli** [comment]
Hey @jneen thanks for the hint. Unfortunately I tried that and it didn't work. 
Apparently the only way to make this work is as following:

1. Change the `_config.yml` to look like the following:

```yaml
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
```
Instead of just
```yaml
markdown: kramdown
highlighter: rouge
```

2. Change the post code to use git like syntax like following:

```markdown
    ---
    layout: post
    title: Hello World
    ---
    ### Hello world

    ```php
    <?php

    echo 'Hello world!';
    ```
```
Any idea why that would be the case?

**Comment by jneen** [comment]
Sorry, this looks like an issue with either Jekyll or Kramdown.  Rouge is just a stylesheet and markup generator.

**Comment by MarcoDeBortoli** [comment]
No need to be sorry, I'm simply trying to get my head around the issue. 
I thought it could be a problem with rouge because that's what I switched to from the default or, even best case scenario, you could know more about Jekyll than me :)

**Comment by jneen** [comment]
I don't use Jekyll personally, so I don't know much about its configuration at all :)

**Comment by MarcoDeBortoli** [comment]
I see I thought you did somehow. Ok I'm going to point the Jekyll guys to this ticket then and see if they can shed some light on this.

**Comment by NARKOZ** [comment]
‏‏‎

**Comment by pyrmont** [comment]
@NARKOZ You commented here and removed the `stale-issue` label. Could you provide more detail on what the issue is at this point?

**Comment by NARKOZ** [comment]
I can't see solarized in themes https://github.com/rouge-ruby/rouge/tree/master/lib/rouge/themes

**Comment by pyrmont** [comment]
@NARKOZ Thanks, got it :)

I realise it's been a long time since your original issue and so this will be disappointing but at this point Rouge relies primarily on its community for feature development and so absent a pull request, this will most likely remained unfulfilled. 

That said, we do really welcome contributions! While we're currently working through the backlog of PRs, we give priority to newer requests. If a theme is proposed, it'll be reviewed in short order.

**Comment by sdavids** [comment]
Solarized light & dark please.
