### ISSUE TITLE
Line highlighting like pygments hl_lines

### ISSUE THREAD

**Issue by bcbroom** [rouge-ruby/rouge#264]
I'm looking for the ability to highlight lines, either to call attention to specific code in a tutorial, or note added code in a running example.

Pygments offers the hl_lines option, such as hl_lines="3 4 5". This adds span element w css class of "hll" to the generated html for that line.

Is this something that has been talked about or planned?

**Comment by jneen** [comment]
Hi! This should be much easier after the formatter refactor for 2.0.

**Comment by citizenmatt** [comment]
I'm also interested in line highlights - is it worth a temp implementation before 2.0 is available? Happy to have a go and send a PR.

**Comment by dmfigol** [comment]
Hi!
Any plans to have this implemented? PR #422 for adding this functionality to <2.0 was rejected, but I can't find in docs that this feature was actually implemented in 2.0.

**Comment by BigChief45** [comment]
Would love this as well....

**Comment by ijean** [comment]
Hello @jneen ,

first I want to say that Rouge seems to be a lot faster (when used from Ruby) than the old Pygments option.

It will be great if you can implement the *hl_lines* option. I've just migrated from an older Jekyll version that was using Pygments to the latest Jekyll which uses Rouge and half of my posts are broken because of this feature missing.

Thanks,
Jean

**Comment by mojavelinux** [comment]
I went ahead and tried to implement this, but hit a problem with line numbering. The HTMLTable formatter, which provides table-based line numbering, delegates to the wrong method on the inner formatter. Instead of delegating to the stream method, it delegates to the span method. This makes it impossible to put a line-wise formatter in between the HTMLTable and HTML formatter. If it delegated to the stream method instead, it would work.

I'll open an issue to address this. Once fixed, I can submit an HTMLHighlightLines formatter (like Pygments).

**Comment by mojavelinux** [comment]
See #1083.

**Comment by mojavelinux** [comment]
Also related is #1084, which is 80% of what is needed for the linewise highlighter.

**Comment by mojavelinux** [comment]
The related issues have been addressed, so I'll see if I can dig up my patch and submit it.

**Comment by mojavelinux** [comment]
I submitted a PR. In the PR, I'm proposing both a new formatter (HTMLLineHighligher) and an enhancement to the HTMLLinewise formatter. The difference is that the HTMLLineHighlighter only wraps the lines specified by the highlight_lines option, whereas the HTMLLinewise formatter wraps all lines (as it currently does) and only adds the additional highlight line class to the highlighted lines. If you think the additional formatter is unnecessary, I can remove it.

**Comment by mojavelinux** [comment]
> Pygments offers the hl_lines option, such as hl_lines="3 4 5"

Since Rouge works in the API space, I felt it was most appropriate for the option (`highlight_lines`) to be a numeric array.
