### ISSUE TITLE
Extend the python lexer for python3

### ISSUE THREAD

**Issue by jneen** [rouge-ruby/rouge#3]

**Comment by thomasboyt** [comment]
From what I've seen so far, the lexer seems to work for most Python 3 syntax, with the exception of the new `yield from` statement in Python 3.3: https://docs.python.org/3/whatsnew/3.3.html#pep-380-syntax-for-delegating-to-a-subgenerator

looks like this is because the `from` keyword immediately kicks the lexer state into "importing" mode, so the fix should be relatively simple: https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/python.rb#L98-L101

I'll take a look at a PR for this soon, but wanted to leave a comment in case I didn't get the chance to come back to this issue :)

**Comment by thomasboyt** [comment]
ack, nevermind, someone did this already! what I get for searching issues instead of PRs :p https://github.com/jneen/rouge/pull/324

**Comment by rumpelsepp** [comment]
`raise ... rom` also causes problems.

```python
raise RuntimeError('Object cannot be packed') from e
```

**Comment by mordervomubel** [comment]
@rumpelsepp are you using the latest git code? I thought I fixed yield and raise in #324 .

**Comment by robin850** [comment]
(Hi there! I guess this issue can certainly be closed thanks to #324 and https://github.com/jneen/rouge/commit/81c08594e8ef08fcc16d5b3968de037321ca49af 😊 )

**Comment by miparnisari** [comment]
This can be closed too @pyrmont 

![image](https://user-images.githubusercontent.com/5374887/58744497-7afc6480-83f8-11e9-95b2-f8b09645e519.png)

![image](https://user-images.githubusercontent.com/5374887/58744498-86e82680-83f8-11e9-9d3d-77d0c9b1b4d1.png)

**Comment by pyrmont** [comment]
Thanks @robin850 and @miparnisari :)
