### ISSUE TITLE
YAML highlighting looks off

### ISSUE THREAD

**Issue by mrzool** [rouge-ruby/rouge#341]
Hello. I'm using rouge with Jekyll and the highlighter isn't working as expected.

I get this output:

![screen shot 2015-11-21 at 19 53 15](https://cloud.githubusercontent.com/assets/6874363/11319939/92e60f9e-9089-11e5-84e8-d6140a5adb57.png)

While I was expecting something more along the lines of this (Github highlighting, where you can clearly tell apart keys from values):

![screen shot 2015-11-21 at 19 55 50](https://cloud.githubusercontent.com/assets/6874363/11319947/e596dfb6-9089-11e5-95a3-c24c764ce351.png)

Is this a bug or am I doing something wrong?

**Comment by ptrikutam** [comment]
I'm having the same issue. Did you figure it out?

**Comment by mrzool** [comment]
More or less, and completely by chance.

I'm telling rouge to consider the YAML blocks as ruby using `{% highlight ruby %}`. This gives me this output:

![screen shot 2016-01-19 at 10 01 39](https://cloud.githubusercontent.com/assets/6874363/12414121/aa8f0ea6-be93-11e5-9053-b66d32800409.png)

It's far from perfect but it's better than the YAML highlighting as it's currently implemented.

Hope this helps.

**Comment by sanderson** [comment]
I've noticed the same thing. I'm working on documenting a project that uses yaml config files heavily and the syntax highlighting isn't great. While specifying the language as `ruby` helps, it's definitely not ideal. Especially because this documentation is open source and others are contributing. The ruby language tag would just confuse others in this specific case.

Would love better yaml highlighting with rouge.

**Comment by sanderson** [comment]
Looks like this is already on @jneen's todo list - issue #38. May want to bump there.

**Comment by miparnisari** [comment]
This looks fine to me now, can we close this issue @pyrmont ?

![image](https://user-images.githubusercontent.com/5374887/58744435-d11cd800-83f7-11e9-8ebc-36ab2b1dc294.png)

**Comment by pyrmont** [comment]
Ooh, another issue closed :) Thanks @miparnisari!
