### ISSUE TITLE
How to display language name in html?

### ISSUE THREAD

**Issue by gaoxiaoliangz** [rouge-ruby/rouge#361]
I'm using rouge in my jekyll blog, when I do something like this

``````
```js
var this_is_js;
```
``````

rouge will not output the language of the code. 

``````
```hahaha
var this_is_hahaha;
```
``````

However, if the language is not identified (let's say the language is hahaha), it seems to output the "language-hahaha" class. and now i want it to output the language name class whether or not it is identified. How can I achieve that?

**Comment by TWiStErRob** [comment]
+1

**Comment by imkean** [comment]
+1

**Comment by jneen** [comment]
The best way to do this would probably be outside of rouge, by modifying whatever template or code is calling into rouge.

**Comment by TWiStErRob** [comment]
@jneen if rouge is outputting the language class for unknown languages, it should be possible to output it for known as well for consistency. Who's generating the wrapping div/code/pre?

**Comment by pyrmont** [comment]
@TWiStErRob Without more information, it's difficult to know who is producing the HTML. Rouge provides formatters but it's possible that Jekyll is providing its own. Do you have the code you're using accessible somewhere? That would make it easier to examine. 

As a point of comparison, I use Jekyll for my blog and as you can see in [this post](https://articles.inqk.net/2019/05/06/how-to-time-machine-backup.html), the `language-<name>` class name is visible. The source for this site is available [here](https://github.com/pyrmont/articles).

**Comment by TWiStErRob** [comment]
Hmm, that's interesting @pyrmont, looks like it's been indeed fixed. But I'm not sure by whom or where.
My latest website indeed has all the `language-*` classes, but I went back to the timestamp of my [+1 comment above](https://github.com/rouge-ruby/rouge/issues/361#issuecomment-184401867) in my repo (https://github.com/TWiStErRob/twisterrob.github.io/commit/84375d4ed40922323d5062ced66ce595b83bf241) and building this `_site` contains no `language-*` for some languages:
![image](https://user-images.githubusercontent.com/2906988/59810141-c7520a80-92fb-11e9-9f44-1ed0027d9762.png)

 * Jekyll <3: works, although I'm not sure I was using rouge back then
 * [Jekyll 3.0.3](https://github.com/github/pages-gem/blob/v48/lib/github-pages.rb#L10): broken
 * [Jekyll 3.7.4](https://github.com/github/pages-gem/blob/v193/lib/github-pages/dependencies.rb#L10): works

You seem to be right about Jekyll's formatter, the weird thing is that [this line](https://github.com/jekyll/jekyll/blob/v3.7.4/lib/jekyll/tags/highlight.rb#L131) in Jekyll didn't significantly change since 3.0.0.

Thanks for the quick response and hints.

**Comment by pyrmont** [comment]
Hmmm, yeah, not sure. Good it's resolved in the end, though! I'll close this one now :)
