### ISSUE TITLE
Bug in R highlighter

### ISSUE THREAD

**Issue by jeroen** [rouge-ruby/rouge#382]
The R highlighter does something weird to the final line of a comment: https://www.opencpu.org/posts/commonmark-fast/

**Comment by BruceZhaoR** [comment]
In R code the keywords,such as `library`, don't render correctly.I check the source file and find that the R keyword is `span.n`,which means normal.  But in the pygments highlighter,it is `span.k`,which meas keywords.
I can't figure out why pygments should be repalced by rouge!

**Comment by klmr** [comment]
@BruceZhaoR The bug report is unconcerned with the lack of highlighting of function names; the issue is, rather, that the last line of the comment is wrongly highlighted:

![screenshot](https://cloud.githubusercontent.com/assets/38931/12816872/d2dc74ba-cb46-11e5-9cc9-7456d140fe34.png)

> I can't figure out why pygments should be repalced by rouge!

The move may have been premature but there are good reasons for it: Jekyll itself runs in Ruby, and having to invoke a separate interpreter to use a library written in another language (Python) is potentially vastly less efficient than using a library written in the same language.

**Comment by BruceZhaoR** [comment]
@klmr Sorry about that! New things always take time to adapt. Hope somebody could implement the highlighting of R function names. :smiley:

**Comment by BruceZhaoR** [comment]
I borrowed a set of js file from RStudio,and now it works fine. If you want to make your R highlight nicer,you could go to look the `brucezhaor.github.io`repository.

**Comment by klmr** [comment]
@BruceZhaoR There’s #383 as well.

**Comment by miparnisari** [comment]
This looks OK in version 3.4.1.

![image](https://user-images.githubusercontent.com/5374887/59401217-d7dc1100-8d4e-11e9-9a0e-96871f625eea.png)

**Comment by pyrmont** [comment]
@miparnisari Yeah, #383 was merged in. Thanks for rooting out these stale issues :)
