### ISSUE TITLE
Colors used in shell code block are too similar

### ISSUE THREAD

**Issue by alexconst** [rouge-ruby/rouge#421]
This is theme dependent and happens at least with _base16_ and in the [demo website](http://rouge.jneen.net/).

The comments and some commands and variable names use very similar colors.

base16 theme screenshot
![](https://i.imgur.com/OLeNK8P.png)

And sample text for testing in the [demo website](http://rouge.jneen.net/)

``` text
# grab your own copy of the recipes
git clone https://github.com/alexconst/packer_recipes
cd packer_recipes/debian-8-jessie-amd64

# Source variables for ISO, checksum, and SSH credentials
source packer_variables.sh
# Because variables make things reusable:
export packer_template="debian-8-jessie-amd64.json"
export packer_builder_selected="jessie-qemu"
# Make sure it's installed and runs:
packer --version
# Validade a template:
packer validate "$packer_template"
# Get an overview of what the template includes (variables, builders, provisioners):
packer inspect "$packer_template"

# Produce machine images for all defined builders:
# Note that this would actually fail for this template, because you can't run different hypervisors simultaneously on the same machine.
# packer build "$packer_template"

# Produce a machine image for the selected builder and keep the logs:
# Note that this is the builder *name* variable (shown with inspect) not the builder *type* variable.
export PACKER_LOG=1
export PACKER_LOG_PATH="/tmp/packer_${packer_builder_selected}.log"
packer build -only="$packer_builder_selected" "$packer_template"

# Save the log file
tmp=$(echo "${packer_template%.*}" | sed 's|\(.*-\).*\(-.*-.*\)|\1*\2|g')
tmp=`eval echo "builds.ignore/${tmp}_${packer_builder_selected}"`
mv $PACKER_LOG_PATH  $tmp/
```

**Comment by jneen** [comment]
Hi @alexconst, thanks for the report. I've saved your snippet so we can refer to it later: http://rouge.jneen.net/pastes/eAWx

**Comment by abellis2** [comment]
This issue is still reproducible.

The following text:
```--header 'Authorization: Bearer {token}''{endpoint}' 'Authorization: Bearer {token}```

Shows up as follows in Slate documentation:
![image](https://user-images.githubusercontent.com/6974342/73879104-b9acaf00-4810-11ea-811e-17437e9f6f6f.png)

**Comment by pyrmont** [comment]
Is the issue here that that the tokens are correct but that the theme doesn't define colours that are legible for these tokens? The problem can be avoided by choosing an alternative theme, right?

**Comment by abellis2** [comment]
@pyrmont You're 100% correct. It mostly seemed odd that the **default** theme for background as well as shell block code were very similar.

**Comment by pyrmont** [comment]
@abellis2 I think things might have changed since this issue was filed. The default theme we use in the internal visual sample tool is 'Thankful Eyes' and the default theme now used in the online dingus is 'Tomorrow' (see [part of the code sample](http://rouge.jneen.net/v3.16.0/shell/IyBQcm9kdWNlIGEgbWFjaGluZSBpbWFnZSBmb3IgdGhlIHNlbGVjdGVkIGJ1aWxkZXIgYW5kIGtlZXAgdGhlIGxvZ3M6CiMgTm90ZSB0aGF0IHRoaXMgaXMgdGhlIGJ1aWxkZXIgKm5hbWUqIHZhcmlhYmxlIChzaG93biB3aXRoIGluc3BlY3QpIG5vdCB0aGUgYnVpbGRlciAqdHlwZSogdmFyaWFibGUuCmV4cG9ydCBQQUNLRVJfTE9HPTEKZXhwb3J0IFBBQ0tFUl9MT0dfUEFUSD0iL3RtcC9wYWNrZXJfJHtwYWNrZXJfYnVpbGRlcl9zZWxlY3RlZH0ubG9nIgpwYWNrZXIgYnVpbGQgLW9ubHk9IiRwYWNrZXJfYnVpbGRlcl9zZWxlY3RlZCIgIiRwYWNrZXJfdGVtcGxhdGUiCgojIFNhdmUgdGhlIGxvZyBmaWxlCnRtcD0kKGVjaG8gIiR7cGFja2VyX3RlbXBsYXRlJS4qfSIgfCBzZWQgJ3N8XCguKi1cKS4qXCgtLiotLipcKXxcMSpcMnxnJykKdG1wPWBldmFsIGVjaG8gImJ1aWxkcy5pZ25vcmUvJHt0bXB9XyR7cGFja2VyX2J1aWxkZXJfc2VsZWN0ZWR9ImAKbXYgJFBBQ0tFUl9MT0dfUEFUSCAgJHRtcC8)).

My sense is that some themes are inevitably going to make more sense than others with particular languages and that if a language isn't working well, the best remedy is to change the theme.

**Comment by abellis2** [comment]
@pyrmont Fair enough. At any rate, we adjusted themes until we got something that worked.

Thanks!

**Comment by pyrmont** [comment]
@abellis2 No worries! Thanks for replying so quickly to my questions :)
