### ISSUE TITLE
Support for TTCN

### ISSUE THREAD

**Issue by wbshen** [rouge-ruby/rouge#462]
There isn't syntax highlighting for TTCN.

Please add support for it, Thanks!

**Comment by jneen** [comment]
Hi @wbshen - could you provide a link to some kind of documentation for what TTCN is? Thanks!

**Comment by wbshen** [comment]
@jneen you can refer to http://www.ttcn-3.org/, Thanks!

**Comment by michele-carignani** [comment]
Hi @jneen,

we would like to help adding TTCN-3 syntax to the project. Could the issue be re-opened or better if we create a new one?

Thanks

**Comment by pyrmont** [comment]
Hi @michele-carignani :) It's been a while since the original issue was opened and the maintainers team is no longer developing lexers in response to requests. I'm sorry about that :(

If you'd like a lexer to be part of Rouge, the best thing to do is submit a pull request with your attempt at it. We have [a guide](https://rouge-ruby.github.io/docs/file.LexerDevelopment.html) on lexer development that can help you get started.

So, rather than reopening this (or filing another) issue, my recommendation would be to take a crack at implementing the lexer and see how you go. Don't worry if your PR isn't perfect. I try to review requests within a week and can provide more assistance once we have some code to discuss.

**Comment by michele-carignani** [comment]
Hi @pyrmont , thank you for the quick answer. Working on a pull request sounds good, we will give it a shot even though we are not Ruby devs :( your review and help will be greatly appreciated!
