### ISSUE TITLE
Support for ASM

### ISSUE THREAD

**Issue by retrohacker** [rouge-ruby/rouge#483]
Currently missing a lexer for ASM files.

In pygments, this lexer handles `asm` and `gas`.

Prior work:
https://bitbucket.org/birkenfeld/pygments-main/src/98fceca1948eed7677fef4e31aeb0c7785531a04/pygments/lexers/asm.py

**Comment by sraboy** [comment]
I started one for x86/NASM in PR #457 so it should be in the next release if no major problems crop up. I don't currently have time to continue working on it so feel free to dive in. Right now, it's pretty basic but it appears to work okay for most of the simpler instructions.

**Comment by retrohacker** [comment]
Ah nice! Looks like pygments handles NASM as a subset of GAS. It switches between modes for the different ASM dialects GAS supports. I may revisit this in the near future, some other pressing stuff on my plate atm :smile:

**Comment by jneen** [comment]
Would love to have this, thanks :]

**Comment by zelivans** [comment]
Some improvements I'd like to suggest to the nasm lexer:
Highlight directives (dword ptr for instance)
Fix brackets usage - for some reason brackets are put in <span class="err"> to me

![image](https://cloud.githubusercontent.com/assets/15815884/23162267/f54c3d1a-f835-11e6-8797-c7233b45bb73.png

I haven't looked into it at all for now so just leaving the suggestions here

**Comment by mafagafogigante** [comment]
I would also really like to see this improvement. @zelivans is correct regarding brackets, apparently they are considered errors.

**Comment by jonhoo** [comment]
Should lines beginning with `#` also be treated as comments? I don't think they currently are in `nasm`.

**Comment by jonhoo** [comment]
I guess actually, comments are `;` in nasm, whereas they are `//` or `/* */` in `.S` assembly files. There's also `#` for preprocessor directives.

**Comment by bernardosulzbach** [comment]
Bad bot. This is still valid AFAIK and there are probably more people still interested in this.

**Comment by bernardosulzbach** [comment]
Well, I will try to make this issue more specific. There certainly is some support for assembly languages in the current master. Therefore, the issue is about the incomplete or inexisting support for some types of assembly languages.

On "VIM - Vi IMproved 8.2 (2019 Dec 12)", these syntax files are included:
```
        asm             GNU assembly (the default)
        asm68k          Motorola 680x0 assembly
        asmh8300        Hitachi H-8300 version of GNU assembly
        ia64            Intel Itanium 64
        fasm            Flat assembly (http://flatassembler.net)
        masm            Microsoft assembly (probably works for any 80x86)
        nasm            Netwide assembly
        tasm            Turbo Assembly (with opcodes 80x86 up to Pentium, and MMX)
        pic             PIC assembly (currently for PIC16F84)
```

As of af801f8cba9d79faa6f5b853be9cfa0bda7ea841, there is support for nasm ([here](https://github.com/rouge-ruby/rouge/blob/af801f8cba9d79faa6f5b853be9cfa0bda7ea841/lib/rouge/lexers/nasm.rb)), nesasm ([here](https://github.com/rouge-ruby/rouge/blob/af801f8cba9d79faa6f5b853be9cfa0bda7ea841/lib/rouge/lexers/nesasm.rb)) and armasm ([here](https://github.com/rouge-ruby/rouge/blob/af801f8cba9d79faa6f5b853be9cfa0bda7ea841/lib/rouge/lexers/armasm.rb)). Notably, there is no support for gas (which Vim calls simply asm)

---

Therefore, two things from this issue (as far as I understand it), still stand out.

## Misinterpretation of [NASM](https://en.wikibooks.org/wiki/X86_Assembly/NASM_Syntax), pointed out above

> Some improvements I'd like to suggest to the nasm lexer:
> Highlight directives (dword ptr for instance)
> Fix brackets usage - for some reason brackets are put in <span class="err"> to me
> 
> ![image](https://cloud.githubusercontent.com/assets/15815884/23162267/f54c3d1a-f835-11e6-8797-c7233b45bb73.png)
> 
> I haven't looked into it at all for now so just leaving the suggestions here

## The lack of support for [GAS](https://en.wikibooks.org/wiki/X86_Assembly/GAS_Syntax)

Self-descriptive.

This issue probably needs to be split into two, if I am correct.

**Comment by pyrmont** [comment]
Two points in response to Bernardo's comment above:

- The broken brackets error is still a problem in NASM ([link](http://rouge.jneen.net/v3.15.0/nasm/bW92IGVheCwgW2VheF0KbW92IGVheCwgW2VheCArIGVieF0KbW92IGVheCwgW2VheCArIGVieCoyXQptb3YgZWF4LCBbZWF4ICsgMTBdCm1vdiBlYXgsIFtlYXggKyBlYngqMiArIDEwXQ)). I'm trying to fix that at the moment.

- The lack of support for GAS is still an issue. As discussion of things has moved around a bit here, I've used the information Bernardo helpfully summarised and filed a new issue for GAS support (#1427).

I'll close this once the NASM issue is fixed.

**Comment by bernardosulzbach** [comment]
> * The broken brackets error is still a problem in NASM ([link](http://rouge.jneen.net/v3.15.0/nasm/bW92IGVheCwgW2VheF0KbW92IGVheCwgW2VheCArIGVieF0KbW92IGVheCwgW2VheCArIGVieCoyXQptb3YgZWF4LCBbZWF4ICsgMTBdCm1vdiBlYXgsIFtlYXggKyBlYngqMiArIDEwXQ)). I'm trying to fix that at the moment.

Interestingly, the samples should include expressions within brackets then, I suppose. I just assumed they worked in general because they are rendered OK when there is just one token inside them.
