### ISSUE TITLE
Add EBNF Syntax Highlighting

### ISSUE THREAD

**Issue by alexanderkiel** [rouge-ruby/rouge#575]
I would like to have nice EBNF syntax highlighting in GitLab. https://en.wikipedia.org/wiki/Extended_Backus–Naur_form

**Comment by nchammas** [comment]
I would guess that EBNF is more popular and relevant than many of the [currently supported languages][1].

I don't know Ruby but I could probably stumble my way through adding support for EBNF with the assistance of an LLM. This would be [against the contributing guide][2], so I guess the path forward for someone interested in this is to try making a plugin.

[1]: https://github.com/rouge-ruby/rouge/blob/2a39d31735fb265b819c7370b35d5bc95c0ffaa8/docs/Languages.md

[2]: https://github.com/rouge-ruby/rouge/blob/2a39d31735fb265b819c7370b35d5bc95c0ffaa8/Contributing.md

**Comment by jneen** [comment]
I'm sure you could also do one on your own! The other guide we have is the Lexer Development Guide, and we have a whole guide on how to set up ruby for rouge.

**Comment by nchammas** [comment]
I'm sure I could, thanks to the documentation you and others have written up. And perhaps I will at some point.

For the time being, however, I am here only because I have a personal blog that runs on Jekyll. I am writing a new post that includes some snippets of EBNF. Seeing that they weren't being highlighted, I searched and found this issue.

I am not a Jekyll contributor and don't know Ruby, so any contributions I make here will be "drive by" contributions. I understand that these are exactly the kind of contributions that tend to burden maintainers. Better to encourage potential contributors to own their work going forward and become part of the "team", so to speak.

At the same time, unless a language is new and/or actively evolving, I would imagine the work to add a new lexer is one and done. But I have no experience with this. Judging from the project's stance on lexer contributions, it seems like I am wrong about that.

In any case, I did use an LLM to add EBNF support and see what the process looks like. I obviously won't submit a pull request for it, but here it is in case others are interested: [REDACTED]

I tweaked this a bit from what was initially generated but confirmed that the tests pass, and I also reviewed the results of the visual test run via `bundle exec puma`.

The LLM did also find some minor typos in the docs, which I'll share here in case you would welcome that as a PR: [REDACTED]

But no hard feelings if not. The contribution policy is clear.

**Comment by jneen** [comment]
Please do not use LLMs to analyze or work on Rouge.

You are correct that maintaining and contributing to this library is work. It is work that you rely on every day, and the general expectation in FOSS is that you contribute as a community member to the software you use. Submitting LLM-generated code or LLM-generated analysis and asking me to clean it up is not a contribution. That is a demand for *extra* free labour. Many people have contributed to this project as their first and maybe even last Ruby project. I am 100% certain you are as capable of this as anyone else.

**Comment by nchammas** [comment]
> Submitting LLM-generated code or LLM-generated analysis and asking me to clean it up is not a contribution. That is a demand for _extra_ free labour.

This is an unfair characterization of what I did just above. I explicitly noted that I would _not_ submit a PR for the EBNF lexer; I was just sharing it as an FYI to others following the thread. And the typos are simple and straightforward fixes that I reviewed. There is no clean up required.

Again, it's OK that you don't want it. But you almost make it sound like I opened some badly mangled PRs containing "AI slop" and then demanded that you accept them.

In any case, I'm not the kind of contributor you're looking for. I will refrain from commenting on this or any other issues going forward.

**Comment by jneen** [comment]
Appreciate it! Nearly all languages, including EBNF, are constantly in flux and this project depends on contributors who deeply understand the code they contribute. If that is not something you are willing to do then yes unfortunately I am not interested in that sort of contribution.
