### ISSUE TITLE
Change from 2.0.7 to 2.1.0 significantly alters output for shell_session

### ISSUE THREAD

**Issue by mjclemente** [rouge-ruby/rouge#810]
I only just noticed this because Github Pages bumped their Rouge dependency. Console code blocks are now rendered differently across my blog.

I understand that the change is likely intentional, as it appears to be due to the switch from the old shell lexer to the newer console lexer. However, for much of my code, I prefer the older rendering. It could be something that I need to address on my side, but I'd appreciate any guidance.

Here's an example of the markdown that's getting rendered differently:

    ```shell_session
    $ tail -f ~/path/to/the/log/file.log
    ```

The old shell_session.rb would render it like this:
![image](https://user-images.githubusercontent.com/5348419/31864458-c11d6342-b72b-11e7-8f25-4d2ea0e963da.png)

After 2.1, it gets rendered like this:
![image](https://user-images.githubusercontent.com/5348419/31864477-e76f4f56-b72b-11e7-8829-5ca683490b47.png)

I'm a huge fan of Rouge, and happy to help work on this (or to be told why the new rendering is better). Thanks for the fantastic tool, and all the work that goes into maintaining and improving it!

**Comment by pyrmont** [comment]
@mjclemente Is this still an issue for you? You should be able to tweak the display by changing your CSS. If you have a look at [rouge.jneen.net](http://rouge.jneen.net) and inspect the output with your input you can see there are different HTML tags used to wrap the different components (sorry, saved pastes aren't working at the moment so I can't link directly).

That said, you might be having an issue because GitHub is using an ancient version of Rouge for GitHub Pages. I'm not sure why that is but, unfortunately, it makes it difficult for us to provide much help. Even if we made a change, we're on version 3.4.1 and it wouldn't be reflected in what you're using :(

**Comment by mjclemente** [comment]
Thanks for checking in on this and all the work you're doing on this project. 

The formatting in the newer versions, as seen on rouge.jneen.net, appears better than what I'm getting. So, as you said, at this point the real issue is the outdated Github Pages dependency. I'll close this out.

**Comment by pyrmont** [comment]
No worries. And I'm sorry not to have had a more satisfying answer :(

I will say that one of my goals with the project is that once we have all our ducks in order over here we can have a look at what's causing GitHub to stay on version 2. That seems less than ideal for everyone involved.
