### ISSUE TITLE
Bitshift without surrounding space is missinterpreted as HEREDOC

### ISSUE THREAD

**Issue by NobbZ** [rouge-ruby/rouge#829]
See http://rouge.jneen.net/pastes/Y1EN for an example.

The final `end` is highlighted as string, not as a keyword like do.

Also a more detailed discussion and a link to real life code suffering from this problem can be found in exercism/exercism.io#3672

**Comment by yilkalargaw** [comment]
it can be better seen by the snippet below

http://rouge.jneen.net/pastes/PQxD

**Comment by NobbZ** [comment]
Sorry, I missed this when stale-bot tagged this issue.

The issue seems to be still there.

**Comment by pyrmont** [comment]
No worries :)

**Comment by pyrmont** [comment]
@NobbZ I'm sorry it took so long to get back to you on this. Forgive the length of this reply but I've had more of a look at the Ruby lexer to investigate what's going on here and I want to write this down somewhere for my benefit as much as anything else.

The problem is the way that Ruby's [StringScanner class](https://ruby-doc.org/stdlib/libdoc/strscan/rdoc/StringScanner.html) works. This is the class that Rouge uses to scan through the input text given to Rouge. Because of a longstanding bug in the class, negative lookbehinds don't work properly. This means that even though the relevant rule in the Ruby lexer

https://github.com/rouge-ruby/rouge/blob/f054b733b8e599c38812d32e98633fb25fb52bbd/lib/rouge/lexers/ruby.rb#L238-L243

begins with a negative lookbehind that should prevent the problem you were seeing, it doesn't because of the bug: the rule matches `<<` regardless of whether or not it is preceded by an alphanumeric character (`\w`).

We did submit a patch to StringScanner that would fix this bug and it was released as part of [v1.02](https://github.com/ruby/strscan/blob/master/NEWS.md#102---2019-10-13). Unfortunately, the fix is disabled by default since it 'breaks' backwards compatibility with code that expects the buggy behaviour. Version 1.02 was released as part of the standard library that forms part of v2.7.0 of Ruby.

As of Rouge v3.17.0, we are not taking advantage of the new behaviour in StringScanner but that's honestly because I forgot it was there until researching this issue. I'll make a new PR that passes the new `fixed_anchor: true` parameter to the instances of `StringScanner.new` in the Rouge codebase. That change can then be discussed further there. (It may be the case that Rouge itself depends on this broken behaviour in places so I'm not sure it's a good idea to enable it prior to the upcoming v4.0 release of Rouge.)

**Comment by pyrmont** [comment]
Here's an example of the lexing working correctly in a version of Rouge where I'm passing `fixed_anchors: true` to the StringScanner initialiser:

<img width="608" alt="bitshift" src="https://user-images.githubusercontent.com/41152/78760812-a35fd280-79bc-11ea-9fee-32293b1ecbc3.png">

**Comment by NobbZ** [comment]
This is still not solved, can this please be tagged to not get autocosed?
