### ISSUE TITLE
Broken java highlighting

### ISSUE THREAD

**Issue by nerro** [rouge-ruby/rouge#831]
Hello,

I found that in java code some utf-8 symbols (like german umlauts) will be rendered as error (with red background text).
Example: http://rouge.jneen.net/pastes/eePb

I'll try to figure it out myself how to fix it.

**Comment by BigChief45** [comment]
Good catch.

However (and correct me if I am wrong), but you shouldn't really write code that contains special characters...

**Comment by dblessing** [comment]
It looks like any Unicode character is acceptable for Java identifiers. I’m
not sure whether it’s good practice or not, but since it’s valid we should
try to support it unless it’s prohibitively difficult. I’m guessing the
offending regex uses \w somewhere. We could potentially switch to
[[:alpha:]] to match any alphabetic character, not just 7-bit ones.

**Comment by nerro** [comment]
@BigChief45 , @dblessing, you both are right. Actually it's not good practice to write code like this, but sometimes you have to generate code for WSDL (https://en.wikipedia.org/wiki/Web_Services_Description_Language).

P.S. It maybe even worse :smile: instead of `ß` you can write `\u00df`.

**Comment by pyrmont** [comment]
This should be something relatively easy to fix. I'll take a look.

**Comment by jneen** [comment]
Comes down to these: Replace them with `[:upper:]` and `[:lower:]` and it should work out

**Comment by pyrmont** [comment]
Thanks @jneen! Will submit a bug fix soon!
