### ISSUE TITLE
Python f-strings not highlighted (PEP 498)

### ISSUE THREAD

**Issue by aldanor** [rouge-ruby/rouge#937]
https://www.python.org/dev/peps/pep-0498/

It would be nice to have syntax inside f-strings properly highlighted, like GH does:

```python
f'{hello} world {int(x) + 1}'
```

**Comment by amigcamel** [comment]
+1

**Comment by Peter200lx** [comment]
This is also related to #942, currently the Python string formatting support could use work. The Python f-string support is extra tricky because inside of the `{}` in an f-string most but not all of regular python formatting applies:
https://docs.python.org/3/reference/lexical_analysis.html#f-strings

**Comment by dvf** [comment]
Just wanted to bump on this to see if anyone is working on it.

**Comment by pyrmont** [comment]
@dvf I had a look into it around the time it was filed and it looked a little difficult (for the reasons @Peter200lx identified in an earlier message).

If you look at [Pygments] (https://github.com/pygments/pygments/blob/95cd525bc6a4fdcfaff243f70ee03d07124ed0cb/pygments/lexers/python.py#L123-129) or [Chroma](https://github.com/alecthomas/chroma/blob/a41c89767d07cc9bd9dce4c5ba2541bbe715f050/lexers/p/python3.go#L44-47), they don't seem to bother treating them differently to other types of strings ([these are the relevant lines](https://github.com/rouge-ruby/rouge/blob/2caa1a09d8eb83188f5517f6070d2ff1631111d8/lib/rouge/lexers/python.rb#L116-119) in our lexer).

How would that be as a solution?
