### ISSUE TITLE
Testing JavaScript with Test262

### ISSUE THREAD

**Issue by jugglinmike** [rouge-ruby/rouge#965]
[Test262](https://github.com/tc39/test262) is the official test suite of the JavaScript language. Although its primary use case is JavaScript run times, its extensive coverage of the language makes it useful for testing other kinds of interpreters. This is especially true for new language features since [tests are a formal requirement at an early stage in the language standardization process](https://tc39.github.io/process-document/). That leads to very good support for new language features.

In recent years, I've been working to integrate Test262 in the test suites of various JavaScript parsers. I'm interested in doing the same for lexing projects like Rouge. Basically, we would attempt to lex each test file and assert that only a subset produced errors.

Right now, Test262 doesn't have the proper metadata to support this use case. It describes "negative syntax" tests generally without distinguishing grammar errors (e.g. `var class`) from lexing errors (e.g. `"unclosed string`). I'd be excited to introduce that information, but I'd like to gauge interest here, first.

Would the maintainers be interested in using Test262 like this?

**Comment by dblessing** [comment]
@jugglinmike Thanks for opening this issue. To be honest, I'm not sure whether this level of testing is necessary for Rouge. We make sure that the sample files do not have errors before merging changes. We also don't need to be 100% correct in all cases because we're a lexer not a parser/compiler. 

That said, if someone else feels strongly or if you can show some ways that this would be beneficial without a lot of overhead, we can consider it further.

**Comment by pyrmont** [comment]
@jugglinmike Hi, I saw this issue as a result of the stale[bot] notification from earlier. Since there wasn't ever a reply to your last message, I wanted to provide a fuller response.

First, I'm sorry it's taken so long to respond and I'm sorry that the initial response was the stale[bot] notification. I joined the group of maintainers a couple of months back and felt that the best way to identify the most pressing issues was to warn about stale ones and close them if there was no response. It's not a great solution.

Second, in terms of the actual issue itself, I agree with @dblessing that Test262 isn't really the right fit for Rouge. Correctness of our lexers is a non-goal of the library and while we don't want to lex things as errors that aren't errors, we're not overly concerned with being more permissive than is strictly correct. This keeps the lexers simpler which is important for both performance and maintainability.

Thank you for opening the issue and wanting to improve Rouge. I'm sorry again for the delay in the response.

**Comment by jugglinmike** [comment]
No worries about the delay. I'm a maintainer myself, so I know how demanding issue triage can be. Thanks for the thoughtful explanation--I eventually decided that testing lexers is a bit out-of-scope for Test262, also: http://mikepennisi.com/blog/2019/just-call-me-johnny-262-seed/

**Comment by pyrmont** [comment]
Wow—after reading that post, I'm amazed at how much work you've done! Thanks again :)
